version: '3.8'

services:
  ruby:
    build:
      args:
        RUBY_VERSION: 3.1.1
      context: .
    depends_on:
      - op-connect-api
      - op-connect-sync
    environment:
      - OP_CONNECT_API_ENDPOINT=http://op-connect-api:8080/v1
    volumes:
      - .:/opt/gem
      - bundle:/usr/local/bundle

  op-connect-api:
    image: 1password/connect-api:latest
    ports:
      - 8080:8080
    volumes:
      - ./1password-credentials.json:/home/opuser/.op/1password-credentials.json
      - op-connect-data:/home/opuser/.op/data
  op-connect-sync:
    image: 1password/connect-sync:latest
    ports:
      - 8081:8080
    volumes:
      - ./1password-credentials.json:/home/opuser/.op/1password-credentials.json
      - op-connect-data:/home/opuser/.op/data

volumes:
  bundle: null
  op-connect-data: null
